src/pymola/backends/casadi/model.py

eg. an equation where alg_state=param

fixes error when pymola attempts to sub an alg state for a parameter

---

src/pymola/backends/casadi/model.py

@jackvreeken What do you think of this solution to #39 ?

implement a simple factor and simplify algorithm for equations

---

src/pymola/backends/casadi/generator.py

with this pr, when a requesting the derivative of an indexed symbol, the slice is "passed through" the derivative operation and applied to the derivative symbol. e.g:
```
get_derivative(MX(a[2]))
```
now returns
```
MX(der(a)[2])
```
Previously, the behavior of get_derivative() was dramatically incorrect in handling this case

get_derivative() now handles case where symbol is already indexed

---

.travis.yml

Travis broke on OSX, this patch fixes it.

Attempt to fix osx travis venv failure.

---

.gitignore
src/pymoca/ast.py
src/pymoca/parser.py

* Annotate parser types to make coding easier.
* Add when equation to AST.
* Ignore some generated files.

Parser types

---

src/pymoca/ast.py
src/pymoca/parser.py
src/pymoca/tree.py

This adds functions to the AST and also does some formatting on the listeners (sorted alphabetically). It also adds a _type field to help with json output of each AST node to see what type each object is when debugging.

Add function equation.

---

.gitignore
.travis.yml
setup.cfg
setup.py
tox.ini

WIP: Add flake8 formatting test

---

.travis.yml
README.md

Fix deployment with TravisCI, and add PyPI installation instructions

---

.coveragerc

Exclude ANTLR-generated code from coverage

---

README.md
src/pymoca/ast.py
src/pymoca/backends/casadi/api.py
test/ast_test.py

Addresses #103 and a part of #102.

AST manipulation API

---

src/pymoca/ast.py
src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/model.py
src/pymoca/parser.py
test/models/CustomUnits.mo
test/parse_test.py

failing test case for custom units

Fix custom unit declaration

---

src/pymoca/backends/casadi/generator.py
src/pymoca/tree.py
test/models/CustomUnits.mo
test/models/ForLoop.mo
test/parse_test.py

Fix mod extended builtin

---

src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/model.py
test/.gitignore
test/gen_casadi_test.py
test/models/ParameterAttributes.mo

Fix caching of variable attributes

---

src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py
src/pymoca/tree.py
test/gen_casadi_test.py
test/models/Annotations.mo
test/models/SimplifyVector.mo

Small fixes

---

src/pymoca/backends/casadi/api.py

Faster reading cache

---

src/pymoca/ast.py

Change the __str__ for some commonly used
ast classes so the debugger shows concise
and clear information on variables.

Improve debugging

---

src/pymoca/Modelica.g4
src/pymoca/generated/ModelicaParser.py

Fix Modelica grammar of external functions

---

src/pymoca/backends/casadi/generator.py

Fix function calls with floats as argument

---

src/pymoca/ast.py

The parent attribute of a class is only there to be able to walk the
tree. One cannot apply modifications to a Class's parent, so excluding
it from the deepcopy is a safe way to avoid unecessarily copying the
entire tree.
The "copy_including_children" method was there to take care of this, but
it turns out that lingering references remain. See e.g. commit 5a743f30
which tried to fix this for the "type" attribute of InstanceClass
objects.

Fix unwanted deepcopies of entire tree

---

.appveyor.yml
.travis.yml
tox.ini

Using a workaround for TravisCI, see https://github.com/travis-ci/travis-ci/issues/9815

Add Python 3.7 to CI

---

src/pymoca/ast.py
src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py
src/pymoca/parser.py
src/pymoca/tree.py
test/gen_casadi_test.py

Second attempt to fix the issues concerning array indexing. 
To be fixed/addressed in this pull request:

Fix indexing 2

---

src/pymoca/backends/casadi/alias_relation.py
src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

Various speedups

---

src/pymoca/backends/casadi/generator.py
src/pymoca/parser.py
test/gen_casadi_test.py
test/models/Logic.mo

Implement logical operators not, and, or, in CasADi generator.

---

src/pymoca/backends/casadi/model.py

In the replace_parameter_expressions simplification step, it was possible
to end up in an endless loop when there are a lot of parameters that have
symbolic values. With the expansions of vectors first (when expand_mx is
True) introduced with 028093f, it is more likely to end up with such
cases.
The CasADi ca.is_equal call will terminate ehen its maximum depth is
reached, and return False. The limit of 100 introduced in adbd468e is not
enough in practice to compare two MX graphs. We therefore increase this
number significantly.
A safeguard is also introduced to prevent an infinite loop from happening
again, by raising an Exception after (currently) 100 iterations.

Fix infinite loop in replace_parameter_expressions

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/SimplifyDifferentiatedState.mo

This is, again, useful for RTC-Tools Channel Flow, so that we can eliminate differentiated states from optimization problems if desired.

Eliminable differentiated states

---

src/pymoca/backends/casadi/api.py

Speed ups for uncaching models with delayed states

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

Fix naming of derivatives when expanding vectors

---

src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

(0.3.x) Fixes for 0.3.1 -> 0.3.2

---

src/pymoca/backends/casadi/model.py

Instead of calling substitute() for every metadata attribute,
we now collect all attributes needing substitution and call
substitute() once.  This saves SWIG function call overhead,
which is especially noticable for models with large numbers
of variables.

CasADi model:  Bundle calls to substitute() on metadata

---

src/pymoca/tree.py
test/models/RedeclarationScopeAlternative.mo
test/parse_test.py

Fix redeclarations with classes inside flattening class

---

src/pymoca/backends/casadi/api.py

There are a few imports in the CasADi backend API that take in the order
of 100 ms. One of which is the (indirect) import of the ANTLR generated
ModelicaParser/Lexer files, which deserialize a binary blob upon import.
We can avoid this import for cached models by lazily importing the
`parser` module.
The other high-latency import is the distutils compiler import, which
will locate the system's copmiler upon import. This import is only
necessary when using codegen to compile a model, so we can instead
lazily import it then.

CasADi: Improve import latency for cached models

---

src/pymoca/backends/casadi/api.py
test/gen_casadi_test.py
test/models/Delay.mo

CasADi: Fix caching of delay expression with constant delay

---

.github/workflows/ci.yml
setup.py
src/pymoca/backends/casadi/api.py
test/gen_casadi_test.py
test/models/Delay.mo
tox.ini

Fix the pipeline for pymoca 0.9.1.

Fix pipeline for 0.9.1

---

src/pymoca/parser.py
test/parse_test.py

~~- [ ] Version the database, so that even if we keep the layout the same, we can make pymoca purge it.~~ Can do this later as well, when needed
Always purge on first run of Pymoca. All accesses to the database are fast afaict, so no need to complicate things (for now).
I think that concurrent access, using Pymoca version with different database layouts, will goes miserably wrong. Should we version the database in the filename to avoid this?

Caching model parsing

---

src/pymoca/parser.py

Cache timing cleanups and improvements
