pymoca/pymoca

.appveyor.yml

Make sure submodules are cloned in appveyor. This is important for the xml PR where there is a required submodule.

Clone submodules in appveyor script.

---

.appveyor.yml

We are currently building up a long queue on appveyor, since it is slower than travis. Is it reasonable to only run 2 of the 4 test cases?
Appveyor was running 4 tests at 3 min each, (once for branch and once for pr), so 24 min.
Travis builds in 10 minutes on average including the wait time.
I configured appveyor to only build the pr and not the branch (appveyor/ci#882) (so it tests the version after merging with master only). This takes us down to 12 min. Then if we reduce to 2 test cases, we get to 6 min.
*Note: Sorry for all of the opening and closing, trying to get the status labels to behave.

Only run 2 cases for appveyor test.

---

.appveyor.yml
.gitmodules

The prevents appveyor from wasting time building branches that are not master. It will still build pull request merges with master.

Set only master in appveyor.

---

src/pymoca/backends/casadi/api.py

When loading cached metadata, the metadata can come in a wide range of
types (e.g. DM). Previously this would sometimes result in runtime errors,
as 'depends_on' is not defined for DM.

Cast cached metadata to MX

---

src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py
src/pymoca/tree.py
test/gen_casadi_test.py
test/models/DelayForLoop.mo

Reconstruct delay_arguments in load_model(), and handle delay arguments

---

test/gen_casadi_test.py
test/models/ArrayExpressions.mo

Fix CasADi numeric equivalence test

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/ParameterAttributes.mo

If a state had a shape that was not (1,) and symbolic parameters in its
attribute expressions, we would attempt to cast the sybolic expression
into a numpy array, throwing an error. We now check for symbolics in the
attribute expressions as well before casting to numpy array.

Fix expand vectors symbolic attribute error

---

src/pymoca/backends/casadi/alias_relation.py

Users might want to pickle or deepcopy pymoca data structures, e.g.
AliasRelation. The linked list underlying the OrderedSet class (used by
AliasRelation and others) would produce max depth recursion errors with
the default behaviour, so we define methods __getstate__ and
__setstate__ to keep behaviour as expected.

Make OrderedSet pickleable and deepcopyable

---

src/pymoca/ast.py
test/models/DeepCopyTimeout.mo
test/parse_test.py

In some specific cases, a reference to the root
ast tree would remain when making a deep_copy.
Each symbol instantiation then takes exponentially
more time.

fix bug where flattening takes exponential time

---

src/pymoca/tree.py
test/models/ModificationTypo.mo
test/parse_test.py

It could happen that a user would apply a symbol modification to e.g.
"my_var", whereas that should have been "My_var". This would silently
fail without applying any modifications at all, which can be very
confusing. Now we check that the targets of the to-be-applied
modifications actually exist.

Check symbol modification target existence

---

src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py

Only with alias detection we would typically know if a delay duration is
an alg_state (or function thereof), or a fixed input. We therefore
should do the check _after_ simplifications, in the newly made
_post_checks() method.

Move delay duration check to post simplification

---

src/pymoca/backends/casadi/alias_relation.py

The direct import of MutableSet from collections is deprecated in Python
3.7, and will be removed in Python 3.8. We should import from
collections.abs instead.

Fix DeprecationWarning of MutableSet import

---

src/pymoca/backends/casadi/api.py
test/gen_casadi_test.py

This uniquely identifies the model cache files, making them easy to e.g.
ignore in .gitignore files.
Closes #154

Add extension to model cache file

---

src/pymoca/backends/casadi/api.py

The depends_on() call is very expensive, and we want to avoid it where
possible. If for some reason the ca.MX symbol is a constant, we can
explicitly check for that, knowing that it does not depend on any
parameters.

Optimization in save model

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/SimplifyLoop.mo

If we cannot detect an alias based on the MX symbols/expression, it may
be because of nested map/if_else/etc. expressions that obscure it. To
expose remaining possible aliases, we expand the equation to SX.
Note that we still do fast checks first, e.g. on the MX graph. The
slowest operation (ca.substitute) is only used as a last resort. This
way the slowdown to the alias detection is is minimal (1.0 - 1.5x), even
for very large models with 100,000+ alias equations.
These extra checks typically result in 1-3% more aliases being detected.
The 'test_simplify_reduce_affine_expression_loop' now finds an
additional alias (x = y[1]). To be able to reliably keep testing the
'reduce affine' portion, the size of 'y' has been increased from 2 to 3.
Closes #55

More aggressive alias checking

---

src/pymoca/backends/casadi/generator.py
test/gen_casadi_test.py

If the first encountered expression of a certain derivative was something
like "der(x[1])", the symbol for the derivative was not properly
inititialized.
Note that if the first encountered expression was instead something like
"der(x)" or "der(x[i])" (like in for loops), the initialization was done
correctly. Encountering an expression like "der(x[1])" afterwards would
then also not lead to any problems.
Closes #163

Fix initialization of derivative symbol in some cases

---

src/pymoca/backends/casadi/model.py

CasADi is_equal() has trouble with if statements causing the loop
to exceed the limit even though the expressions have converged.
Therefore, until this issue has been addressed by the CasADi developers,
we raise a warning rather than an exception when this happens.

Warn instead of raise exception when exceeding substitute loop limit

---

src/pymoca/tree.py
test/parse_test.py

Inheriting from oneself does not make any sense, so we detect it and raise
an Exception.
Closes #152

Fix infinite recursion if class inherits itself

---

setup.py

The path separator on Windows is ";", whereas we used to just use ":"
without checking what platform we were running on. Python conveniently
offers the correct separator to use with the "os.pathsep" variable.

Fix ANTLR generation on Windows

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/MatrixExpressions.mo

This fixes an issue where direct matrix assignments were broken.

CasADi model, symbol values:  Interpret lists of lists of numbers as DM

---

src/pymoca/backends/casadi/generator.py
src/pymoca/tree.py
test/gen_casadi_test.py
test/models/Interpolate.mo

Interpolation is not officially supported by the Modelica core, whence the proposed builtins are prefix with the string "_pymoca_": _pymoca_interp1d and _pymoca_interp2d.

Proposal to add two custom builtin functions to do 1D and 2D interpolation

---

src/pymoca/backends/sympy/generator.py

Check modelica code for exponent character (^) and replace it with python exponent character (**)

Correct modelica exponent character ^

---

.appveyor.yml

For some reason, an old pip version for Python 3.5 fails to install
pymoca and its dependencies on AppVeyor. Note that we still test Python
3.5 (and its randomly ordered dicts) on Linux with Travis.

AppVeyor: Skip Python 3.5 run due to pip errors

---

src/pymoca/backends/casadi/api.py

When we unpickle a CasADi object, it performs a check that it can
actually deserialize it. If it does not succeed, it raises a
RuntimeException saying so. We do not need to bother users with this
exception, and instead just recompile the modile.

CasADi: Fix detection of cache for invalid CasADi version

---

src/pymoca/tree.py

Before we would only raise an AssertionError when we were not able to
resolve a ComponentRef in a connect clause. This error would not provide
any information about _what_ connect statement was wrong, which made it
hard to debug. We now print out some (not perfect) information about the
failing statement.

Tree: Give information about failing connect equations

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

The default value of `expand_mx` is False, not True. We should also
raise an Exception, as the error is user facing and can commonly occur.

CasADi/simplify: Fix assertion on expand_mx

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/SmallNominal.mo

Before this commit, the default nominal was 1.0. If a user explicitly
set a nominal of e.g. 0.1 on a variable, but would not set a nominal on
an alias thereof, the alias detection would end up with a nominal of
1.0.
This problem is easily fixed by setting the default nominal to 0.0,
which would mean that it is not set.

CasADi: Fix small nominals on aliases by making default nominal zero

---

MANIFEST.in
requirements.txt
setup.py
tox.ini

Split installation dependencies per backend

---

setup.py

ANTLR 4.8 was recently released (with no signifant changes to the Python
target), which lead to the error "ANTLR runtime and generated code
versions disagree: 4.8!=4.7". Apparently we have to make sure that the
right version of ANTLR is installed, not just a minimum requirement.

Fix ANTLR version requirement

---

src/pymoca/ast.py
src/pymoca/backends/casadi/model.py
src/pymoca/backends/sympy/generator.py
src/pymoca/backends/xml/generator.py
test/gen_casadi_test.py
test/models/ConflictingAliasStart.mo

Instead of just blindly overwriting the start attribute with that of the
lastest alias, we should check if there is a conflict to avoid suprises.
Note that we cannot exhaustively check for conflicts, because if the
user sets the canonical state's start attribute explicitly to zero, it
will still overwrite it with that of the alias.
Also note that the order in which we loop over aliases is random (due to
the usage of a set), so the order in which messages appear and what
conflict they report can be different. This also means that, in the case
the user does not set a non-zero start attribute on the canonical state
(that is the first encountered alias), but does do so on multiple of its
aliases, the eventual start attribute of the canonical state cannot be
known in advance. This situation …

CasADi: Warn if start attribute of alias conflicts

---

src/pymoca/backends/casadi/_options.py
src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py

I am not sure if writing some documentation is a plan for the future. Nevertheless, I think that getting a list of the available options could come quite handy, especially for newcomers. I generated this list based on the get methods used to access the options dictionary.
I could also write a description of each option in the docString if this sounds useful.

Add method to API in order to retrieve the default compiler options

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

The aliasing of algebraic states to parameters already worked as
expected, but that for constants did not yet. This commit fixes the
latter such that aliasing behavior to constants is similar to that of
parameters.
Two tests have been added. Note that only ConstantAlias model failed
before this commit, and that the ParameterAlias model is added for
completion and easy comparison (i.e. expected aliasing behavior is very
similar in both tests).
Closes #218

CasADi: Fix aliasing of algebraic states to constants

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

The previous logic would fail in the following situation:
- in iteration 1: A is aliased to B and A is deleted
- in iteration 2: B is aliased to C, the canonical variable of A is then C. 
The check `alias in old_alias_relation.aliases(canonical)` which in these case is `A in old_alias_relation.aliases(C)` returns False and an error is raised when A is not found in all_states
I was not able to create a simple example to showcase this. I have this problem with a rather big model. In any case, this solution works with the previous tests and it is rather similar from a logical point of view.

CasADi: bugfix on iterative detect alias

---

src/pymoca/backends/casadi/api.py
src/pymoca/backends/casadi/generator.py
src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py
test/models/ParameterAttributes.mo
test/models/Simplify.mo

Some options are:
1. Keep as is; `model.parameters` contains all parameters regardless of type.  CasADi functions are a function of all parameters.
2. `model.parameters` contains all parameters regardless of type.  CasADi functions are a function of only the numeric parameters.
3. Add `model.string_parameters`, as a separate parameter group for non-numeric parameters. Not an input to any of the CasADi functions.
EDIT:
Options 3 is probably the cleanest one, so going with that one.

CasADi: Support string parameters in model

---

src/pymoca/backends/casadi/_options.py
src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

Some software handles derivate states rather differently from regular
states. For example, the derivative states might not actually be
individual symbols collocated in time, but instead just the difference
between two collocated instances of the associated state (divided by a
time interval).
When an algebraic state is an alias of a derivative state, with the
canonical state he derivative, processing of the aliased (algebraic)
state can then easily fail when it relies on there being associated
collocated symbols. This commit adds an options to disallow aliasing to
derivative states for such software.

CasADi/Simplify: Add option to (dis)allow aliasing derivative states

---

src/pymoca/backends/casadi/api.py

According to the specification, Modelica files should always be stored
in UTF-8. If we do not set the encoding when reading Modelica files, we
could get errors on files with special (non-ASCII) characters on
e.g. Shift-JIS platforms.

CasADi/API: Fix always reading .mo files as UTF-8

---

src/pymoca/backends/casadi/alias_relation.py
test/alias_relation_test.py

The test case that this commit adds describes the problem in a minimal
way. The issue was caught specifically with a single circular pipe
network (all discharges equal), which before this commit resulted in:
- No canonical state of any discharge
- All discharges were part of the algebraic states
- All alias equations for discharges were removed from the model
Basically this meant that every discharge became a free symbol, which is
obviously very wrong. Such networks and sets of equations are not
uncommon, and are definitely not limited to discharges (but all types of
flow quantities).
The fix is rather simple; if the alias relationship we add already
exists, we skip it.

AliasRelation: Fix handling of circular alias dependencies

---

src/pymoca/backends/casadi/generator.py
test/gen_casadi_test.py

Since version 1.20, NumPy warns about the use of np.int as an alias of
int. Instead, the suggestion is to just use `int` as the type specifier.

Fixes related to NumPy 1.20 (deprecations, behavior changes)

---

src/pymoca/backends/casadi/api.py

A recent CasADi version changed the error message when a pickled MX
function cannot be unpickled due to a version mismatch. This commit
updates the check so that instead of (re)raising the respective
RuntimeError from CasADi, we just recompile the model.

CasADi/API: Fix invalid cache check due to CasADi version mismatch

---

src/pymoca/backends/casadi/_options.py
src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

There are few simplification options affecting parameters. These are for
example the inline parameters with symbolic values (i.e. a function of
other parameter values) into the equations they occur. That particular
simplification has a side-effect of removing the parameter after
inlining, to avoid confusion if the user wants to change its value
(which wouldn't have any effect). Sometimes however, it is useful to
have:
1. All parameter values resolved (where possible) to numeric values and
2. Have all these parameter values inlined in the min/max/etc metadata
2. Still keep the parameter names + values around
To that end, we introduce a new simplification
`resolve_parameter_values`, disabled by default.

CasADi/Simplify: Add `resolve_parameter_values` option 

---

src/pymoca/backends/casadi/api.py

Converting a huge matrix of metadata to MX first, and indexing after,
can result in it not resolving to a numeric value. The safer way is to
keep it a ca.DM instance, and only convert the indexed result to MX.

CasADi: Fix cached metadata values not matching uncached

---

AUTHORS
LICENSE
src/pymoca/ast.py
test/ast_test.py

Add `__repr__` to all AST `Node`'s to improve debugging.
In the process I also changed some `__str__` methods. This could break any code that depended on the prior `str()` format. In particular, the `__str__` method of `Node` itself (that is inherited by many subclasses) now tries to trim out trivial/empty attributes to make a more readable json printout. This "feature" could be reverted if necessary.
The the `ComponentRef` class method `concatenate` is changed to a regular method and now takes a single `ComponentRef` instead of a list. This does not appear to be used in any other pymoca code, but again could break other code using it. I do use it in the added AST tests, but the main reason for changing this is efficiency for an upcoming `import` addition. This could be easily reverted if …

Modelica: Add __repr__ to AST Nodes

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

When substituting metadata, we prefer to end up with the type of the
corresponding Variable.
For instance, when the expression `0.25 * x ** 2` is resolved for `x =
1.0`, we would end up with a ca.MX value instead of a float. Due to
NumPy 1.20 changing the behavior around arrays [0], it is no longer
possible to "just" use this ca.MX in e.g. array expressions. This commit
makes sure that we end up with a Python float instead.
[0] See also 649e22ad

CasADi/Simplify: Cast to Python type when substituting metadata

---

src/pymoca/parser.py
test/parse_test.py

Before this change, `parser.parse()` would continue on its merry
way trying to build an AST when there were syntax errors from ANTLR.
At the least it is wasted time.
Also fixed type errors found by mypy and in the process found that
there was a bit of duplicate code between `ASTListener` members
`ast_result` and `file_node`.

Don't build AST if parse fails

---

.gitmodules
src/pymoca/ast.py
src/pymoca/backends/casadi/model.py
src/pymoca/tree.py
test/models/Attributes.mo
test/parse_test.py

PR #246 implements the `import` statement, so we can remove the workaround in `ast.Class.find_class` that converts any references to `SI` and `Modelica` to `Real` and import the proper definitions from the Modelica Standard Library.
This adds the Modelica Standard Library versions 3 and 4 as testing targets and three additional unit tests to flatten classes that import SI units. They are isolated enough that they don't trigger other current pymoca parsing or flattening issues.
In addition to the existing `unit` in `ast.Symbol.ATTRIBUTES`, `quantity` and `displayUnit` are added to support all of the SI units in MSL version 3 and 4. Related to this, the CasADi backend has a small change to future-proof it from attributes added to `Symbol` in the front end.
To support the use of SI units …

Modelica: Support SI units

---

.github/workflows/ci.yml
setup.cfg
setup.py
src/pymoca/ast.py
src/pymoca/backends/xml/generator.py
tools/compiler.py
tools/create_conda_env.sh
tox.ini

This fixes #250 which are some issues identified by tox (which I just got up and running on my machine):
- Some Python scripts in the newly-added Modelica Standard Library submodules were triggering flake8 errors, so excluded them
- Typing syntax incompatible with Python 3.5 were reverted to type comments

CI/CD: Fix tox issues and bump Python version

---

test/compiler_test.py
tools/compiler.py

This fixes #252 where there was a pickle version issue in CasADi model cache when switching from newer to older Python versions. This just fixes the compiler test to be more robust, not the CasADi backend.
This also fixes a related bug where "True" and "False" strings passed on the command line were not properly converted to bool, and so as non-zero length strings, they were always recognized as True.

Tools/compiler: Fix test and True/False options

---

src/pymoca/tree.py
test/parse_test.py

Class comments (class "description" in Modelica Spec 3.5 grammar) should be retained during flattening because they are quite helpful in describing the purpose of the class to humans and therefore backends should have access through the AST. Previously comments were dropped.

Modelica: preserve class comments in flattening

---

src/pymoca/backends/sympy/generator.py
test/gen_sympy_test.py

Add the Modelica `time` built-in variable to the SymPy generator. The test case feeds a time-varying input to the existing SpringSystem model. This fixes #256.

SymPy: Add Modelica `time` support

---

src/pymoca/ast.py
src/pymoca/parser.py
test/ast_test.py

Adds methods to `ast.Class` to add/remove initial equations (as regular equations have). These can be useful in backend code to convert start attributes to initial equations. Also cleans up related superfluous code in the parser callbacks.
Tests that intitial equations are correctly parsed and new add/remove methods work correctly. This somewhat duplicates CasADi initial condition tests, but using a ModelicaCompliance example.

Modelica: Add initial equation add/remove methods

---

setup.py

Jinja2 is an explicit dependency of the SymPy backend, yet was not listed. The minimal version requirement added is that of when the "import jinja2" line was added, i.e. around May 2017.
Note that the lack of this listing does not usually lead to issues, because Jinja2 is installed as part of JupyterLab. JupyterLab is a dependency for the "examples" extra, and therefore also part of the "all" extra that is used by the CI/CD pipeline.

setup.py: Fix Jinja2 dependency for SymPy backend

---

src/pymoca/backends/casadi/generator.py
test/gen_casadi_test.py

Parser support for this was added in 81b4a51 .
Note that a negative prefix was already supported by the CasADi backend.

CasADi: Support + expression prefix

---

src/pymoca/backends/sympy/generator.py
src/pymoca/backends/sympy/runtime.py

Removes duplicate SymPy symbols that the sympy generator backend creates for Modelica output variables. They are already created in the variables section of the Jinja template.
SymPy 1.12 aparently added a check for duplicate symbols. SymPy throws a `ValueError: duplicate symbols given` exception in `sympy.solve()` that causes `test_estimator` in `gen_sympy_test` to fail.

SymPy: Fix generator duplicate variable creation

---

.github/workflows/ci.yml
setup.py

Python 3.7 is EOL.
Also, the recent CasADi 3.6.3 release supports Python up to 3.11. Since we do not pin the max Python and CasADi versions, we need to test up to Python 3.11.

Bump Python >= 3.8 and test to 3.11

---

.github/workflows/ci.yml

This adds a GitHub release action to track along with the PyPI releases.
It uses `softprops/action-gh-release` which is 1 of 4 actions recommended by the now archived GitHub-developed action
[`actions/create-release`](https://github.com/actions/create-release) and has the most stars and contributors of the 4.
The flag is turned on to auto-generate GitHub release notes to keep maintenance to a minimum while Pymoca is at its current level of development. I expect we will want to have some human intervention in creating release notes as we get closer to the 1.0 milestone and it looks very doable to gradually add more of that along with the auto-generated content. You can check out the auto-generated notes in the 0.10.0.dev6 release while this PR is being reviewed, but I intend to delete that …

CI/CD: Add GitHub release action

---

src/pymoca/backends/casadi/model.py
test/gen_casadi_test.py

The symbol "value" was not instantiated when the parameter value was a list.
Furthermore, we were only looking at lists and not also at NumPy arrays. We force convert from list to array in this if-branch, and also in some places in the code. We therefore have to make sure the condition catches both lists and np.ndarrays.

CasADi/Simplify: Fix `resolve_parameter_values` for list/array values

---

tools/compiler.py

This allows the compiler to be used when sympy and/or casadi are not installed. A use case is testing just the parse and/or flatten steps. It should also speed up the startup of the compiler a little, even when one of the backends is used, and becomes more and more important as additional backends are added.
The implementation simply moves the sympy and casadi backend imports to where they are used.

Compiler: Delay backend imports

---

src/pymoca/tree.py
test/parse_test.py

This fixes a problem where modifying the value of a symbol of a type that is inherited from another type would fail during instantiation with a `pymoca.tree.ModificationTargetNotFound`.
This also expands the "Processing failed for symbol" message given when symbol type instantiation fails in `build_instance_tree`. It now includes the message from the underlying exception to give a more specific reason for the failure.
This is related to 4dd9048 that fixed inherited types for two test cases using SI units in MSL 3 and 4, but they did not include testing value *modification* of the inherited types.
Closes #300.

Tree: Fix inherited type value modification

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
tox.ini

Wanted something to automatically check for style conformance before pushing to GitHub and the [pre-commit Python package](https://pypi.org/project/pre-commit/) seems to do the trick.
In addition, since there are GitHub actions for pre-commit, I propose changing the CI to use pre-commit also so local and GitHub configuration for style checks are consistent and in once place. This is the 2nd commit in this PR, so it can be dropped if we decide not to do that.
If we adopt for GitHub CI, there is a [pre-commit GitHub action](https://github.com/marketplace/actions/pre-commit) and there is also a separate [pre-commit CI service](https://pre-commit.ci) that says it is free for open source.

Style: Use pre-commit

---

test/parse_test.py

When running on Github Actions, the first and second hit time have a tendency to be equal, possibly for reasons related to mounted/network storage.
To make sure that the cache is hit, we can also check whether the log messages indicate as such, instead of just looking at a forced update of the last hit time.
Note that this commit does not fix the failing of the test, it just adds an additional check to better understand what is going on.

CI/CD: Fix cache test

---

.github/workflows/ci.yml
pyproject.toml

Try Python 3.12 in the test matrix.
Also since there are so many versions of Python active (3.8 to 3.12), it seems excessive to test every version. This changes the matrix to just three versions: 3.8, 3.10, 3.12. For future updates, I envision picking min, max, and median of the supported Python versions.

CI/CD: Update max Python to 3.12

---

src/pymoca/parser.py
test/parse_test.py

Testing over in https://github.com/jackvreeken/pymoca-test-1 and https://github.com/jackvreeken/pymoca-test-2.
Current commit of this PR has been stress tested in https://github.com/jackvreeken/pymoca-test-2 for the last 12 hours (and will keep on running).

Fix Windows runs on Github Actions

---

pyproject.toml
test/notebooks/Spring.ipynb

This replaces #327 as a fix for #324,
* adding the missing optional `[examples]` dependency on `control==0.10.0`
* pinning the version because of the as-yet unreleased upstream change in [a9415a0](https://github.com/python-control/python-control/commit/a9415a036d4e34d18446d6cf3c3fda093859736d) (2024-04-04)
* though that will still have a [graceful deprecation](https://github.com/python-control/python-control/blob/2d1f514d5b56b07877a879517e828d965777c5f8/control/rlocus.py#L163)
* calling `control.rlocus` from here with `kvect`
* rather than previous `klist` because that doesn't work in `control 0.10.0` or
* the future `gains` because that isn't yet available in `control 0.10.0`
```python
import control
import pymoca.parser
import pymoca.backends.sympy.generator as generator
ast = …
```

Control 0 10 0

---

pyproject.toml

The `control` package version 0.10.0 we pinned in 0902b78 is only available for Python 3.10 and above. We still want to support Python 3.8 and 3.9, so we extend the range to the latest version of `control` that did so as well.

Fix installation regression on Python 3.8 / 3.9

---

.github/workflows/ci.yml

GitHub Actions was giving deprecation warnings about NodeJS 16, and that we should update to NodeJS 20. We therefore update all actions to their latest versions.

CI/GA: Update actions to their latest versions

---

src/pymoca/backends/casadi/api.py

Version 10.0.26100 of the Windows SDK introduced changes to how INFINITY and NAN are defined in `math.h`. This resulted in NAN no longer being a compile-time constant, and codegen'd code failing compilation the most recent `windows-latest` image. The workaround is to define _UCRT_NOISY_NAN, which restores the old behavior.
Closes #338

codegen: Workaround MSVC NaN constantness bug

---

.github/workflows/ci.yml
.pre-commit-config.yaml
antlr/antlr_build.py
pyproject.toml
src/pymoca/backends/xml/analysis.py
src/pymoca/backends/xml/model.py
src/pymoca/backends/xml/sim_scipy.py
src/pymoca/tree.py

Tests that ran OK 2 days ago are now failing on Python 3.8 on Windows when there have been no changes to tested code. Since Python 3.8 is end of life, let's bump min Python to 3.9 and max to 3.13 and see how it tests out.

CI/CD: Update Python >=3.9 and <=3.13

---

.github/workflows/ci.yml
MANIFEST.in
README.md
pyproject.toml

Change from the old setup.py-based build to something consistent with current Python packaging standards (though the instructions are poorly documented). I guess we have not done a deploy since the change to pyproject.toml, so this is the first time we are seeing the issue.
EDIT: We also fixed some issues with the build and upload to PyPI including the rendering of the README on PyPI.

CI/CD: Fix deploy consistent with pyproject.toml

---

pyproject.toml
setup.py

We are currently getting "0+unknown" from the PyPI package. Also, we are getting the setuptools-generated version number in development mode (no "dirty" flag currently needed for the parse cache code).
This fixes it by adding setup.py back in to generate _version.py and removes the setuptools dynamic versioning from pyproject.toml so that we get the version number from versioneer for both the build artifacts and _version.py.

CI/CD: Fix `pymoca.__version__`
